[project]
site_name = "ninejs"
repo_url = "https://github.com/y-sunflower/ninejs"
site_url = "https://y-sunflower.github.io/ninejs/"
site_description = "Bringing interactivity to plotnine"
site_author = "Joseph Barbier"
extra_css = ["stylesheets/style.css"]
nav = [
  { "Home" = "index.md" },
  { "Gallery" = [
    "gallery/index.md",
    "gallery/coal-production.md",
    "gallery/mondrian.md",
    "gallery/europe-co2.md",
    "gallery/area-hover-to-show.md",
    "gallery/south-france-restaurants.md",
    "gallery/climate-vulnerability-co2.md",
    "gallery/household-wealth.md"
  ] },
  { "Guides" = [
    "guide/tooltip.md",
    "guide/onclick.md",
    "guide/css.md",
    "guide/javascript.md",
    "guide/animation.md",
    "guide/quarto.md",
    "guide/marimo.md",
    "guide/shiny.md",
    "guide/streamlit.md",
    "guide/positron.md",
    "guide/troubleshooting.md",
  ] },
  { "API Reference" = [
    "reference/interactive.md",
    "reference/css.md",
    "reference/javascript.md",
  ] },
  { "Contributing" = "contributing.md" },
]

[project.theme]
language = "en"
favicon = "images/favicon.png"
logo = "https://github.com/JosephBARBIERDARNAL/static/blob/main/python-libs/ninejs/image.png?raw=true"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.footnote.tooltips",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.tabs",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "navigation.prune",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
repo = "fontawesome/brands/github"
favicon = "https://github.com/JosephBARBIERDARNAL/static/blob/main/python-libs/ninejs/favicon.ico?raw=true"

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["."]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_source = false

[project.markdown_extensions.attr_list]

[project.markdown_extensions.md_in_html]
